program export_tests;
(*
  Covers PasClaw.Cmd.Export -- the cross-runtime adapter that renders
  PasClaw's MEMORY.md + SCARS.md + skill manifests + sandbox policy
  into the rules files Claude Code / Cursor / Gemini CLI / Zed AI /
  AGENTS.md consumers already look for at the repo root.

  We pin:
    - canonical body includes a memory section when MEMORY.md exists
    - canonical body includes a scars section when SCARS.md exists
    - canonical body enumerates skills with their frontmatter description
    - cursor target prepends a YAML frontmatter block (alwaysApply: true)
    - non-cursor targets do not
    - the generated marker appears on the first non-frontmatter line
    - empty $PASCLAW_HOME produces a body with the "nothing configured" hint

  We test through the exposed RenderExportBody so the contract is
  pinned at the function boundary, not at "what files get written
  where" -- those are covered by the smoke target.
*)

{$IFDEF FPC}{$MODE DELPHI}{$ENDIF}
{$H+}

uses
  SysUtils, Classes,
  PasClaw.Cmd.Export;

procedure Fail(const Msg: string);
begin
  WriteLn('FAIL: ' + Msg);
  Halt(1);
end;

procedure AssertContains(const Haystack, Needle, Msg: string);
begin
  if Pos(Needle, Haystack) <= 0 then
    Fail(Msg + ' (needle "' + Needle + '" not found)');
end;

procedure AssertNotContains(const Haystack, Needle, Msg: string);
begin
  if Pos(Needle, Haystack) > 0 then
    Fail(Msg + ' (needle "' + Needle + '" was present but should not be)');
end;

procedure WriteText(const Path, Content: string);
var
  Sl: TStringList;
begin
  ForceDirectories(ExtractFilePath(Path));
  Sl := TStringList.Create;
  try
    Sl.Text := Content;
    Sl.SaveToFile(Path);
  finally
    Sl.Free;
  end;
end;

function FixtureHome: string;
{ Honour the PASCLAW_HOME the Makefile exported when launching us so
  the test sandbox lines up with what GetHome inside RenderExportBody
  will resolve to. If the operator runs the test directly with
  PASCLAW_HOME unset we fall back to a temp-dir path -- but the
  Makefile target sets it explicitly so the test stays hermetic in
  CI. }
var
  H: string;
begin
  H := GetEnvironmentVariable('PASCLAW_HOME');
  if H <> '' then
    Result := H
  else
    Result := IncludeTrailingPathDelimiter(GetTempDir(False)) +
              'pasclaw-export-test-home';
end;

procedure WipeFixture;
begin
  { Crude recursive wipe. The test fixture is shallow; we never put
    anything precious here. }
  if DirectoryExists(FixtureHome) then
    ExecuteProcess('/bin/sh', ['-c', 'rm -rf ' + FixtureHome], []);
end;

procedure SetupFixture;
begin
  { Wipe + repopulate the synthetic PASCLAW_HOME. Each section
    populated below corresponds to one branch in RenderExportBody --
    if any of these reads breaks, the assertions downstream will
    surface it immediately. }
  WipeFixture;
  ForceDirectories(FixtureHome);

  WriteText(IncludeTrailingPathDelimiter(FixtureHome) +
              'workspace/memory/MEMORY.md',
            '### Patterns observed (2026-06-09)' + sLineBreak +
            '' + sLineBreak +
            '- Do not run `npm test` in pnpm repos' + sLineBreak);

  WriteText(IncludeTrailingPathDelimiter(FixtureHome) +
              'workspace/memory/SCARS.md',
            '# SCARS' + sLineBreak +
            '' + sLineBreak +
            '## §NPM-IN-PNPM-REPO' + sLineBreak +
            '' + sLineBreak +
            '**Symptom:** npm WARN config production' + sLineBreak);

  WriteText(IncludeTrailingPathDelimiter(FixtureHome) +
              'workspace/skills/hello/SKILL.md',
            '---' + sLineBreak +
            'name: hello' + sLineBreak +
            'description: Greets the operator on demand.' + sLineBreak +
            '---' + sLineBreak +
            '' + sLineBreak +
            '# Hello skill body' + sLineBreak);
end;

procedure SetupEmptyFixture;
begin
  WipeFixture;
  ForceDirectories(FixtureHome);
end;

procedure TestPopulatedBodyHasAllSections;
var
  Body: string;
begin
  SetupFixture;
  Body := RenderExportBody('agents');
  AssertContains(Body, '<!-- generated by: pasclaw export',
                 'generated marker present');
  AssertContains(Body, '# Agent rules for this repository',
                 'header heading present');
  AssertContains(Body, '## Project memory',
                 'memory section present');
  AssertContains(Body, 'Patterns observed (2026-06-09)',
                 'memory body included');
  AssertContains(Body, '## Recurring failures (SCARS)',
                 'scars section present');
  AssertContains(Body, '§NPM-IN-PNPM-REPO',
                 'scars anchor included');
  AssertContains(Body, '## Skills available in this workspace',
                 'skills section present');
  AssertContains(Body, 'hello',
                 'skill name listed');
  AssertContains(Body, 'Greets the operator',
                 'skill description pulled from frontmatter');
end;

procedure TestCursorTargetHasFrontmatter;
{ Cursor needs the YAML block at the top -- alwaysApply: true is
  what makes the rule live in every prompt rather than only when
  the model goes looking for it. The frontmatter MUST come before
  the generated marker; Cursor parses the block as YAML and the
  marker would otherwise leak into the YAML grammar. }
var
  Body: string;
  GeneratedAt, FrontEnd: Integer;
begin
  SetupFixture;
  Body := RenderExportBody('cursor');
  AssertContains(Body, '---' + sLineBreak +
                       'description:', 'frontmatter opens at top');
  AssertContains(Body, 'alwaysApply: true', 'alwaysApply set');
  GeneratedAt := Pos('<!-- generated by:', Body);
  FrontEnd    := Pos('---' + sLineBreak + sLineBreak, Body);
  if GeneratedAt <= 0 then Fail('cursor body has no generated marker');
  if FrontEnd    <= 0 then Fail('cursor body has no frontmatter close');
  if GeneratedAt < FrontEnd then
    Fail('generated marker leaks into Cursor YAML frontmatter');
end;

procedure TestNonCursorTargetHasNoFrontmatter;
var
  Body: string;
begin
  SetupFixture;
  Body := RenderExportBody('claude');
  if Pos('alwaysApply:', Body) > 0 then
    Fail('claude body should not carry Cursor-style frontmatter');
end;

procedure TestRuntimeLabelPersonalises;
{ The intro sentence says "Claude Code" / "Cursor" / "Gemini CLI" /
  "Zed AI" depending on target. Small touch -- but readers notice. }
var
  Bc, Bg, Bz, Ba: string;
begin
  SetupFixture;
  Bc := RenderExportBody('claude');
  Bg := RenderExportBody('gemini');
  Bz := RenderExportBody('zed');
  Ba := RenderExportBody('agents');
  AssertContains(Bc, 'Claude Code',    'claude label');
  AssertContains(Bg, 'Gemini CLI',     'gemini label');
  AssertContains(Bz, 'Zed AI',         'zed label');
  AssertContains(Ba, 'the agent',      'generic agents label');
end;

procedure TestEmptyHomeBodyDropsEmptySections;
{ With no MEMORY.md / SCARS.md / skills, the corresponding sections
  must NOT appear -- the body should be sandbox-only (sandbox is
  populated from config defaults, which enable the built-in shell
  denylist and block_private_networks even on a fresh install).
  The generated marker is the smoke test that the export emitter
  ran at all. }
var
  Body: string;
begin
  SetupEmptyFixture;
  Body := RenderExportBody('agents');
  AssertContains(Body, '<!-- generated by:',
                 'generated marker still present');
  AssertNotContains(Body, '## Project memory',
                    'empty memory section is dropped');
  AssertNotContains(Body, '## Recurring failures (SCARS)',
                    'empty scars section is dropped');
  AssertNotContains(Body, '## Skills available in this workspace',
                    'empty skills section is dropped');
  { Sandbox always renders because the default TConfig flips on
    ShellDenyEnabled + BlockPrivateNetworks -- exporting those
    defaults is the right behaviour (foreign runtime sees the same
    floor PasClaw enforces on itself). }
  AssertContains(Body, '## Sandbox policy',
                 'sandbox section emits config-default policies');
end;

begin
  TestPopulatedBodyHasAllSections;
  TestCursorTargetHasFrontmatter;
  TestNonCursorTargetHasNoFrontmatter;
  TestRuntimeLabelPersonalises;
  TestEmptyHomeBodyDropsEmptySections;
  WriteLn('export_tests: OK');
end.
