(*
  PasClaw.Cmd.Export -- render PasClaw's internal project memory into
  the rules / context files other agent runtimes already look for.

  Borrowed from Abbasi-Alain/atlas: a project that already has a
  curated MEMORY.md + SCARS.md + skill manifests + a sandbox policy
  is the source of truth for "how this agent should behave in this
  repo". Other runtimes (Claude Code, Cursor, Gemini CLI, Zed AI, the
  emerging AGENTS.md convention) read sidecar files at the repo root
  for the same kind of guidance. Re-exporting PasClaw's state into
  those filenames means a teammate who happens to be using a
  different runtime picks up the same rules without having to
  install PasClaw.

  Targets supported (one canonical body, format-specific framing):

    agents   -> ./AGENTS.md                 (de-facto cross-runtime
                                              standard; also read by
                                              Claude Code as a
                                              fallback)
    claude   -> ./CLAUDE.md                  (Claude Code primary)
    cursor   -> ./.cursor/rules/agent.mdc    (Cursor; YAML frontmatter
                                              required so it gets
                                              alwaysApply=true)
    gemini   -> ./GEMINI.md                  (Gemini CLI)
    zed      -> ./.zed/agent.md              (Zed AI)
    all      -> all of the above             (default)

  Re-running overwrites the previously-exported file -- each output
  carries a `<!-- generated by: pasclaw export -->` marker on the
  first line so the operator (and reviewers) can tell at a glance
  that the file is regenerated rather than hand-authored. Any
  hand-edits the operator wants to keep belong in PasClaw's source
  state (workspace/memory/MEMORY.md, SCARS.md, the skill manifests)
  -- which is the whole point of `export`: one source, many
  consumers.

  Out of scope: bidirectional sync. Pulling rules out of a foreign
  CLAUDE.md / AGENTS.md and folding them back into MEMORY.md is a
  different feature (`pasclaw import`), and the answer to "what
  happens on round-trip" is unclear enough that I'd rather punt on
  it than ship a leaky abstraction. For now, export is one-way.
*)
unit PasClaw.Cmd.Export;

{$IFDEF FPC}{$MODE DELPHI}{$ENDIF}
{$H+}
{$IFDEF FPC}
  {$CODEPAGE UTF8}
  {$WARN IMPLICIT_STRING_CAST OFF}
  {$WARN IMPLICIT_STRING_CAST_LOSS OFF}
{$ENDIF}

interface

function Cmd_Export_Run(const Argv: array of string): Integer;

(* Render the canonical body (header + memory + scars + skills +
   sandbox) for a given target into a string. Exposed so a test can
   pin the contract without having to actually write files. *)
function RenderExportBody(const Target: string): string;

implementation

uses
  SysUtils, Classes,
  PasClaw.CliUI,
  PasClaw.Config,
  PasClaw.Utils;

const
  GENERATED_MARKER = '<!-- generated by: pasclaw export -- do not hand-edit; '
                  +  'change the source under $PASCLAW_HOME/workspace/ and re-run -->';

procedure Help;
begin
  PrintLn('Usage: pasclaw export [target] [options]');
  PrintLn('  Render PasClaw''s memory + skills + sandbox policy into the rules');
  PrintLn('  files other agent runtimes look for at the repo root.');
  PrintLn('');
  PrintLn('Targets:');
  PrintLn('  agents     ./AGENTS.md                  (cross-runtime convention)');
  PrintLn('  claude     ./CLAUDE.md                  (Claude Code)');
  PrintLn('  cursor     ./.cursor/rules/agent.mdc    (Cursor; YAML frontmatter)');
  PrintLn('  gemini     ./GEMINI.md                  (Gemini CLI)');
  PrintLn('  zed        ./.zed/agent.md              (Zed AI)');
  PrintLn('  all        write all of the above       (default)');
  PrintLn('');
  PrintLn('Options:');
  PrintLn('  --to <dir>     Write into <dir> instead of the current directory');
  PrintLn('  --stdout       Print the rendered body to stdout (no file written)');
  PrintLn('  -h, --help     Show this help');
end;

{ ------------------------ section gatherers ------------------------ }

function ReadFileIfExists(const Path: string): string;
{ Slurp a small text file into a string. Returns '' if the file is
  missing or unreadable -- export is best-effort; an absent
  MEMORY.md just means that section gets dropped. }
var
  Sl: TStringList;
begin
  Result := '';
  if not FileExists(Path) then Exit;
  Sl := TStringList.Create;
  try
    try
      Sl.LoadFromFile(Path);
      Result := Sl.Text;
    except
      Result := '';
    end;
  finally
    Sl.Free;
  end;
end;

function MemorySection: string;
var
  Body: string;
begin
  Body := ReadFileIfExists(JoinPath(JoinPath(GetHome, 'workspace/memory'),
                                    'MEMORY.md'));
  if Trim(Body) = '' then Exit('');
  Result := '## Project memory' + sLineBreak +
            sLineBreak +
            'Pinned by `pasclaw learn --write`; treat the patterns below as ' +
            'durable hints rather than transient session notes.' + sLineBreak +
            sLineBreak +
            Trim(Body) + sLineBreak +
            sLineBreak;
end;

function ScarsSection: string;
var
  Body: string;
begin
  Body := ReadFileIfExists(JoinPath(JoinPath(GetHome, 'workspace/memory'),
                                    'SCARS.md'));
  if Trim(Body) = '' then Exit('');
  Result := '## Recurring failures (SCARS)' + sLineBreak +
            sLineBreak +
            'Anchor names are stable; cite them in commits and PRs to link a fix ' +
            'back to the failure it addresses.' + sLineBreak +
            sLineBreak +
            Trim(Body) + sLineBreak +
            sLineBreak;
end;

function ListSkillManifests: TStringList;
{ Walk workspace/skills/<name>/SKILL.md so we can report the
  per-skill name + description without depending on a parser. For
  the export we only need the first paragraph -- the model can
  reach for fs_read to pull the full body if it wants. }
var
  Root: string;
  Search: TSearchRec;
  EntryDir, SkillFile: string;
begin
  Result := TStringList.Create;
  Result.Sorted := True;
  Root := JoinPath(GetHome, 'workspace/skills');
  if not DirectoryExists(Root) then Exit;
  if FindFirst(IncludeTrailingPathDelimiter(Root) + '*', faAnyFile,
               Search) = 0 then
  begin
    try
      repeat
        if (Search.Name = '.') or (Search.Name = '..') then Continue;
        if (Search.Attr and faDirectory) = 0 then Continue;
        EntryDir  := JoinPath(Root, Search.Name);
        SkillFile := JoinPath(EntryDir, 'SKILL.md');
        if FileExists(SkillFile) then
          Result.Add(Search.Name + '=' + SkillFile);
      until FindNext(Search) <> 0;
    finally
      FindClose(Search);
    end;
  end;
end;

function ExtractFrontmatterField(const Body, Field: string): string;
{ Pluck `Field: value` from a YAML-frontmatter block at the top of
  Body. Stops at the closing `---`. Trims surrounding whitespace
  and surrounding quotes. Returns '' if not found. The skill
  manifest format only uses a flat key:value block so we don't
  need a full YAML parser. }
var
  Sl: TStringList;
  i: Integer;
  Line, Prefix, Val: string;
  InFront: Boolean;
begin
  Result  := '';
  InFront := False;
  Prefix  := LowerCase(Field) + ':';
  Sl := TStringList.Create;
  try
    Sl.Text := Body;
    for i := 0 to Sl.Count - 1 do
    begin
      Line := Trim(Sl[i]);
      if i = 0 then
      begin
        if Line <> '---' then Exit;
        InFront := True;
        Continue;
      end;
      if Line = '---' then Break;
      if not InFront then Break;
      if Pos(Prefix, LowerCase(Line)) = 1 then
      begin
        Val := Trim(Copy(Line, Length(Prefix) + 1, MaxInt));
        if (Length(Val) >= 2) and (Val[1] = '"') and (Val[Length(Val)] = '"') then
          Val := Copy(Val, 2, Length(Val) - 2);
        if (Length(Val) >= 2) and (Val[1] = '''') and (Val[Length(Val)] = '''') then
          Val := Copy(Val, 2, Length(Val) - 2);
        Result := Val;
        Exit;
      end;
    end;
  finally
    Sl.Free;
  end;
end;

function SkillsSection: string;
{ Enumerate skills the agent has access to, with a one-line
  description pulled from each SKILL.md's frontmatter. We don't
  inline the bodies -- those can be large -- but we tell the
  consuming agent where to find them. }
var
  Manifests: TStringList;
  i: Integer;
  Name, Path, Body, Desc: string;
  Cfg: TConfig;
  HasLegacy: Boolean;
  j: Integer;
begin
  Result := '';
  Manifests := ListSkillManifests;
  try
    HasLegacy := False;
    Cfg := LoadConfig;
    try
      if Length(Cfg.Skills) > 0 then HasLegacy := True;
      if (Manifests.Count = 0) and (not HasLegacy) then Exit('');
      Result := '## Skills available in this workspace' + sLineBreak +
                sLineBreak +
                'Each skill is a self-contained capability the agent can load ' +
                'on demand. Read the full manifest body before using one -- the ' +
                'frontmatter description below is intentionally short.' + sLineBreak +
                sLineBreak;
      for i := 0 to Manifests.Count - 1 do
      begin
        Name := Manifests.Names[i];
        Path := Manifests.ValueFromIndex[i];
        Body := ReadFileIfExists(Path);
        Desc := ExtractFrontmatterField(Body, 'description');
        if Desc = '' then Desc := '(no description)';
        Result := Result + Format('- **%s** -- %s', [Name, Desc]) + sLineBreak +
                  Format('  Manifest: `%s`', [Path]) + sLineBreak;
      end;
      if HasLegacy then
      begin
        for j := 0 to High(Cfg.Skills) do
        begin
          if not Cfg.Skills[j].Enabled then Continue;
          Result := Result + Format('- **%s** -- (legacy config entry, source=%s)',
                                    [Cfg.Skills[j].Name, Cfg.Skills[j].Source]) + sLineBreak;
        end;
      end;
      Result := Result + sLineBreak;
    finally
      Cfg.Free;
    end;
  finally
    Manifests.Free;
  end;
end;

function SandboxSection: string;
{ Surface PasClaw's sandbox policy so a foreign runtime sees the
  same boundaries (read-only paths, denylisted commands). The
  foreign runtime can't enforce them -- this is documentation, not
  enforcement -- but having them visible cuts down on "the agent
  on Cursor cheerfully ran the command we'd blocked in PasClaw"
  surprises. }
var
  Cfg: TConfig;
  Sb: TSandboxPolicy;
  i: Integer;
  Lines: TStringList;
begin
  Result := '';
  Cfg := LoadConfig;
  try
    Sb := Cfg.Sandbox;
    if (not Sb.RestrictToWorkspace) and
       (not Sb.ShellDenyEnabled) and
       (Length(Sb.CustomShellDeny) = 0) and
       (Length(Sb.AllowReadPaths) = 0) and
       (Length(Sb.AllowWritePaths) = 0) then
      Exit('');
    Lines := TStringList.Create;
    try
      Lines.Add('## Sandbox policy (informational)');
      Lines.Add('');
      Lines.Add('PasClaw enforces these boundaries on its own tool calls. The ' +
                'foreign runtime reading this file does NOT enforce them -- they ' +
                'are surfaced here so the agent knows what to avoid by convention.');
      Lines.Add('');
      if Sb.RestrictToWorkspace then
      begin
        if Sb.Workspace <> '' then
          Lines.Add(Format('- Operate inside workspace: `%s`', [Sb.Workspace]))
        else
          Lines.Add('- Operate inside the current working directory');
        if Sb.AllowReadOutsideWorkspace then
          Lines.Add('- Reads outside the workspace are tolerated; writes are not');
      end;
      if Length(Sb.AllowReadPaths) > 0 then
      begin
        Lines.Add('- Additional readable paths:');
        for i := 0 to High(Sb.AllowReadPaths) do
          Lines.Add(Format('  - `%s`', [Sb.AllowReadPaths[i]]));
      end;
      if Length(Sb.AllowWritePaths) > 0 then
      begin
        Lines.Add('- Additional writable paths:');
        for i := 0 to High(Sb.AllowWritePaths) do
          Lines.Add(Format('  - `%s`', [Sb.AllowWritePaths[i]]));
      end;
      if Sb.ShellDenyEnabled then
        Lines.Add('- Built-in shell command denylist is on (`rm -rf /`, ' +
                  '`mkfs`, `dd of=`, etc.)');
      if Length(Sb.CustomShellDeny) > 0 then
      begin
        Lines.Add('- Additional denied shell substrings:');
        for i := 0 to High(Sb.CustomShellDeny) do
          Lines.Add(Format('  - `%s`', [Sb.CustomShellDeny[i]]));
      end;
      if Sb.BlockPrivateNetworks then
        Lines.Add('- Outbound HTTP to RFC1918 / link-local / loopback ranges is blocked');
      Lines.Add('');
      Result := Lines.Text;
    finally
      Lines.Free;
    end;
  finally
    Cfg.Free;
  end;
end;

{ ------------------------ format renderers ------------------------ }

function CanonicalBody(const RuntimeLabel: string): string;
{ The body all five targets share. RuntimeLabel goes in the
  intro sentence so the file feels addressed to whoever is reading
  it ("This file is for Claude Code" vs "This file is for Cursor")
  -- a small thing, but consumers notice. }
var
  Mem, Scars, Skills, Sandbox: string;
begin
  Mem     := MemorySection;
  Scars   := ScarsSection;
  Skills  := SkillsSection;
  Sandbox := SandboxSection;

  Result := '# Agent rules for this repository' + sLineBreak +
            sLineBreak +
            Format('This file gives %s the same project context PasClaw uses ' +
                   'internally. It is regenerated by `pasclaw export`; edit the ' +
                   'source files under `$PASCLAW_HOME/workspace/` rather than ' +
                   'this file -- changes here are clobbered on the next export.',
                   [RuntimeLabel]) + sLineBreak +
            sLineBreak;
  if Mem     <> '' then Result := Result + Mem;
  if Scars   <> '' then Result := Result + Scars;
  if Skills  <> '' then Result := Result + Skills;
  if Sandbox <> '' then Result := Result + Sandbox;

  if (Mem = '') and (Scars = '') and (Skills = '') and (Sandbox = '') then
    Result := Result +
              '_(no memory, scars, skills, or sandbox policy configured -- run ' +
              '`pasclaw learn`, install some skills, or set ' +
              '`sandbox.restrict_to_workspace=true` to populate this file)_' +
              sLineBreak;
end;

function RuntimeLabelOf(const Target: string): string;
begin
  if      Target = 'claude' then Result := 'Claude Code'
  else if Target = 'cursor' then Result := 'Cursor'
  else if Target = 'gemini' then Result := 'Gemini CLI'
  else if Target = 'zed'    then Result := 'Zed AI'
  else                           Result := 'the agent';
end;

function RenderExportBody(const Target: string): string;
{ Wrap the canonical body in the format-specific framing each
  target expects. Cursor is the only target that needs more than
  a comment header (its `.mdc` rule files want a YAML frontmatter
  block declaring alwaysApply so the rule lands in every prompt). }
var
  Body, Frontmatter: string;
begin
  Body := CanonicalBody(RuntimeLabelOf(Target));

  if Target = 'cursor' then
  begin
    { Cursor's `.mdc` format: frontmatter then markdown. alwaysApply
      = true ensures the rule lives in every prompt rather than
      only when the model asks for it. The description is what
      Cursor shows in its rules picker. }
    Frontmatter := '---' + sLineBreak +
                   'description: PasClaw-exported project memory, SCARS, skills, ' +
                   'and sandbox policy' + sLineBreak +
                   'alwaysApply: true' + sLineBreak +
                   '---' + sLineBreak +
                   sLineBreak;
    Result := Frontmatter + GENERATED_MARKER + sLineBreak + sLineBreak + Body;
    Exit;
  end;

  Result := GENERATED_MARKER + sLineBreak + sLineBreak + Body;
end;

function OutputPathFor(const Target, BaseDir: string): string;
begin
  if      Target = 'agents' then Result := JoinPath(BaseDir, 'AGENTS.md')
  else if Target = 'claude' then Result := JoinPath(BaseDir, 'CLAUDE.md')
  else if Target = 'cursor' then
    Result := JoinPath(JoinPath(JoinPath(BaseDir, '.cursor'), 'rules'),
                       'agent.mdc')
  else if Target = 'gemini' then Result := JoinPath(BaseDir, 'GEMINI.md')
  else if Target = 'zed'    then
    Result := JoinPath(JoinPath(BaseDir, '.zed'), 'agent.md')
  else                           Result := '';
end;

function WriteExport(const Target, BaseDir: string): Boolean;
var
  Path, Body: string;
  Sl: TStringList;
begin
  Path := OutputPathFor(Target, BaseDir);
  if Path = '' then Exit(False);
  if not DirectoryExists(ExtractFilePath(Path)) then
    ForceDirectories(ExtractFilePath(Path));
  Body := RenderExportBody(Target);
  Sl := TStringList.Create;
  try
    Sl.Text := Body;
    try
      Sl.SaveToFile(Path);
      Result := True;
      PrintLn(Ansi.Green + '✓ ' + Ansi.Reset + Format('wrote %s', [Path]));
    except
      on E: Exception do
      begin
        Result := False;
        PrintLnErr(Ansi.Red + Format('failed writing %s: %s', [Path, E.Message]) +
                   Ansi.Reset);
      end;
    end;
  finally
    Sl.Free;
  end;
end;

const
  AllTargets: array[0..4] of string = ('agents', 'claude', 'cursor', 'gemini', 'zed');

function IsKnownTarget(const T: string): Boolean;
var
  i: Integer;
begin
  for i := Low(AllTargets) to High(AllTargets) do
    if T = AllTargets[i] then Exit(True);
  Result := False;
end;

function Cmd_Export_Run(const Argv: array of string): Integer;
var
  Target, BaseDir: string;
  ToStdout: Boolean;
  i, Failures: Integer;
  Body: string;
begin
  Target   := 'all';
  BaseDir  := GetCurrentDir;
  ToStdout := False;

  i := 0;
  while i <= High(Argv) do
  begin
    if (Argv[i] = '-h') or (Argv[i] = '--help') then
    begin
      Help;
      Exit(0);
    end;
    if (Argv[i] = '--to') and (i < High(Argv)) then
    begin
      BaseDir := Argv[i + 1];
      Inc(i, 2);
      Continue;
    end;
    if Argv[i] = '--stdout' then
    begin
      ToStdout := True;
      Inc(i);
      Continue;
    end;
    if (Argv[i] <> '') and (Argv[i][1] <> '-') then
    begin
      Target := Argv[i];
      Inc(i);
      Continue;
    end;
    PrintLnErr(Ansi.Red + 'unknown export argument: ' + Argv[i] + Ansi.Reset);
    Exit(1);
  end;

  if (Target <> 'all') and (not IsKnownTarget(Target)) then
  begin
    PrintLnErr(Ansi.Red + 'unknown export target: ' + Target + Ansi.Reset);
    Help;
    Exit(1);
  end;

  if ToStdout then
  begin
    if Target = 'all' then
    begin
      PrintLnErr(Ansi.Red +
                 '--stdout requires a single target (agents|claude|cursor|gemini|zed)' +
                 Ansi.Reset);
      Exit(1);
    end;
    Body := RenderExportBody(Target);
    Write(Body);
    Exit(0);
  end;

  if not DirectoryExists(BaseDir) then
  begin
    PrintLnErr(Ansi.Red + 'target directory does not exist: ' + BaseDir +
               Ansi.Reset);
    Exit(1);
  end;

  Failures := 0;
  if Target = 'all' then
  begin
    for i := Low(AllTargets) to High(AllTargets) do
      if not WriteExport(AllTargets[i], BaseDir) then Inc(Failures);
  end
  else
  begin
    if not WriteExport(Target, BaseDir) then Inc(Failures);
  end;

  if Failures > 0 then Result := 1 else Result := 0;
end;

end.
