#!/usr/bin/env python3
"""Regenerate the screenshots in docs/screenshots/.

Two steps, because the gateway has to be running between them:

    python3 docs/screenshots/capture.py init  /tmp/pasclaw-shots
    build/pasclaw serve --addr 127.0.0.1 --port 8330 &      # PASCLAW_HOME=...
    python3 docs/screenshots/capture.py shoot docs/screenshots --home /tmp/pasclaw-shots

`init` writes the fixture config and a MEMORY.md. `shoot` seeds the running
gateway with projects and one finished conversation, then captures.

The seeding is the point. An empty gateway photographs a blank chat pane and
"No projects yet." -- the first version of these screenshots did exactly
that, and documented the chrome and nothing else. So the fixture content is
created here rather than described in prose and left to the reader.

The conversation is produced through the `relay` provider: the reply below
is written by this script, not generated by a model. That keeps the recipe
reproducible with no API key and no network, and it is why the README says
plainly that the content is fixture data.
"""

import argparse
import json
import os
import sys
import threading
import time
import urllib.error
import urllib.request

PORT_DEFAULT = 8330

# --------------------------------------------------------------------------
# fixture content
# --------------------------------------------------------------------------

CONFIG = {
    "default_provider": "relay",
    "default_model": "relay-operator",
    # The relay needs an entry in `providers`, not just a default_provider:
    # NewProviderFromConfig calls FindProvider first and fails with
    # 'no provider entry for "relay"' before the catalog is ever consulted.
    "providers": [{"name": "relay", "kind": "relay"}],
    "auto_router": {"enabled": False},
    "memory_distill_enabled": True,
}

MEMORY_MD = """# Project memory

- PasClaw is an Object Pascal AI agent framework targeting FPC and Delphi.
- The release checklist lives at docs/release.md; step 3 runs before step 2.
- Windows installers are built from the Delphi project, not from make.
"""

PROJECTS = [
    ("Release Dashboard", "A small web app that charts PasClaw release download counts."),
    ("Log Triage",        "Cluster recurring failures out of session transcripts."),
    ("Docs Site",         "Static docs generated from the markdown under docs/."),
]

SESSION_ID = "docs-screenshot-fixture"

QUESTION = "What order do the release steps run in, and where is the checklist?"

ANSWER = """The checklist lives at **docs/release.md**, and the ordering is \
deliberate: **step 3 runs before step 2**.

I found this in workspace memory rather than by reading the file, so if the \
checklist has changed on disk since that note was written, the file wins.

What I did *not* check: whether docs/release.md still exists, or whether \
steps 1 and 4 have their own ordering constraints — the note only covers the \
3-before-2 case."""

SHOTS = [
    ("web-ui-chat",   "/",         None,     []),
    ("web-ui-memory", "/",         "MEMORY", ["MEMORY.md"]),
    ("web-desktop",   "/desktop",  None,     []),
]

W, H = 1600, 1000


# --------------------------------------------------------------------------
# init
# --------------------------------------------------------------------------

def cmd_init(args):
    home = os.path.abspath(args.home)
    mem = os.path.join(home, "workspace", "memory")
    os.makedirs(mem, exist_ok=True)
    with open(os.path.join(home, "config.json"), "w") as f:
        json.dump(CONFIG, f, indent=2)
    with open(os.path.join(mem, "MEMORY.md"), "w") as f:
        f.write(MEMORY_MD)
    print("wrote %s/config.json and workspace/memory/MEMORY.md" % home)
    print("now start the gateway against it:")
    print("  PASCLAW_HOME=%s build/pasclaw serve --addr 127.0.0.1 --port %d &"
          % (home, PORT_DEFAULT))
    return 0


# --------------------------------------------------------------------------
# seeding a running gateway
# --------------------------------------------------------------------------

def post(url, obj, timeout=300, headers=None):
    h = {"Content-Type": "application/json"}
    h.update(headers or {})
    req = urllib.request.Request(
        url, data=json.dumps(obj).encode(), method="POST", headers=h)
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return r.read().decode("utf-8", "replace")


def get(url, timeout=15):
    with urllib.request.urlopen(url, timeout=timeout) as r:
        return r.read().decode("utf-8", "replace")


def seed_projects(base):
    existing = json.loads(get(base + "/v1/projects")).get("projects", [])
    have = {p.get("title") for p in existing}
    for title, desc in PROJECTS:
        if title in have:
            continue
        post(base + "/v1/projects", {"title": title, "description": desc})
    print("projects: %d" % len(json.loads(get(base + "/v1/projects"))["projects"]))


def relay_worker(base, stop, answered):
    """Hold the relay poll stream open and answer each job.

    The stream IS the worker's registration: if it closes, the gateway
    requeues whatever that worker had in flight. So one long-lived
    connection here, and the reply goes out on a separate one.
    """
    req = urllib.request.Request(base + "/v1/relay/poll",
                                 headers={"X-Relay-Worker-Id": "screenshot-fixture"})
    try:
        stream = urllib.request.urlopen(req, timeout=120)
    except Exception as exc:                                    # noqa: BLE001
        answered.append(("error", "could not attach relay worker: %r" % exc))
        return
    for raw in stream:
        if stop.is_set():
            return
        line = raw.decode("utf-8", "replace").strip()
        if not line.startswith("data: "):
            continue
        try:
            job = json.loads(line[6:])
        except ValueError:
            continue
        n = len(job.get("messages", []))
        if n <= 1:
            # First turn: call memory_search, so the transcript shows a tool
            # round-trip rather than a bare question and answer.
            body = {
                "content": "", "finish_reason": "tool_calls",
                "usage": {"prompt_tokens": 3100, "completion_tokens": 28},
                "tool_calls": [{
                    "id": "c1", "type": "function",
                    "function": {"name": "memory_search",
                                 "arguments": json.dumps(
                                     {"query": "release checklist steps", "k": 5})},
                }],
            }
        else:
            body = {"content": ANSWER, "finish_reason": "stop",
                    "usage": {"prompt_tokens": 3400, "completion_tokens": 96}}
        try:
            post(base + "/v1/relay/respond/" + job["id"], body, timeout=30)
            answered.append(("ok", job["id"]))
        except Exception as exc:                                # noqa: BLE001
            answered.append(("error", "respond failed: %r" % exc))
            return
        if n > 1:
            return


def seed_conversation(base):
    stop = threading.Event()
    answered = []
    worker = threading.Thread(target=relay_worker, args=(base, stop, answered),
                              daemon=True)
    worker.start()
    time.sleep(1.0)                       # let the stream register first

    result = {}

    def ask():
        try:
            # Named session, not the stateless default: without this header
            # /v1/chat answers and saves nothing, the sidebar stays on "no
            # saved chats", and the captured chat pane is blank -- which is
            # exactly how the first version of this recipe failed to
            # reproduce its own checked-in screenshot.
            result["body"] = post(
                base + "/v1/chat", {"message": QUESTION},
                headers={"X-PasClaw-Session": SESSION_ID})
        except Exception as exc:          # noqa: BLE001
            result["error"] = repr(exc)

    t = threading.Thread(target=ask, daemon=True)
    t.start()
    t.join(timeout=180)
    stop.set()

    for kind, detail in answered:
        if kind == "error":
            raise SystemExit("relay seeding failed: " + detail)
    if "error" in result:
        raise SystemExit("chat request failed: " + result["error"])
    if "body" not in result:
        raise SystemExit("chat request timed out -- is a relay worker already "
                         "attached to this gateway?")
    print("conversation: %d relay turn(s) answered" % len(answered))


# --------------------------------------------------------------------------
# capture
# --------------------------------------------------------------------------

def launch(p):
    """Playwright's own browser by default.

    An explicit path is an ESCAPE HATCH, not the default: a hardcoded
    revision directory is wrong on any machine whose Playwright installed a
    different one, which is most of them. Set PASCLAW_SHOT_CHROME when a
    browser is preinstalled somewhere Playwright will not find it.
    """
    override = os.environ.get("PASCLAW_SHOT_CHROME")
    if override:
        return p.chromium.launch(executable_path=override, args=["--no-sandbox"])
    try:
        return p.chromium.launch(args=["--no-sandbox"])
    except Exception as exc:                                    # noqa: BLE001
        raise SystemExit(
            "could not launch Chromium: %s\n\n"
            "Install Playwright's browser:\n"
            "    python3 -m playwright install chromium\n"
            "or point at an existing one:\n"
            "    PASCLAW_SHOT_CHROME=/path/to/chrome %s\n"
            % (exc, " ".join(sys.argv)))


def cmd_shoot(args):
    from playwright.sync_api import sync_playwright

    base = args.base
    out = os.path.abspath(args.out)
    os.makedirs(out, exist_ok=True)

    try:
        get(base + "/v1/health")
    except Exception as exc:                                    # noqa: BLE001
        raise SystemExit("no gateway at %s (%r) -- start one first, see "
                         "`capture.py init`" % (base, exc))

    if not args.no_seed:
        seed_projects(base)
        seed_conversation(base)

    failures = []
    with sync_playwright() as p:
        browser = launch(p)
        for name, path, click, then in SHOTS:
            page = browser.new_page(viewport={"width": W, "height": H},
                                    device_scale_factor=1)
            errs = []
            page.on("pageerror", lambda e: errs.append(str(e)))
            page.on("console",
                    lambda m: errs.append(m.text) if m.type == "error" else None)
            page.goto(base + path, wait_until="networkidle", timeout=30000)
            page.wait_for_timeout(2500)
            if click:
                page.locator("nav button", has_text=click).first.click()
                page.wait_for_timeout(1800)
            for label in then:
                page.get_by_text(label).first.click()
                page.wait_for_timeout(1500)
            dest = os.path.join(out, name + ".png")
            page.screenshot(path=dest)
            size = os.path.getsize(dest)
            print("%-16s %7d bytes  title=%r" % (name, size, page.title()))
            if errs:
                # A screenshot of a page that threw is a screenshot of a bug.
                # Collecting these and exiting 0 would let an unattended
                # regeneration quietly replace the images with broken ones.
                for e in errs[:5]:
                    print("    JS ERROR: %s" % e[:200])
                failures.append((name, len(errs)))
            page.close()
        browser.close()

    if failures:
        raise SystemExit("FAILED: %s" % ", ".join(
            "%s (%d JS error(s))" % (n, c) for n, c in failures))
    print("ok: %d screenshots, no page errors" % len(SHOTS))
    return 0


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    sub = p.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("init", help="write the fixture PASCLAW_HOME")
    s.add_argument("home")
    s.set_defaults(fn=cmd_init)

    s = sub.add_parser("shoot", help="seed a running gateway, then capture")
    s.add_argument("out")
    s.add_argument("--base", default="http://127.0.0.1:%d" % PORT_DEFAULT)
    s.add_argument("--no-seed", action="store_true",
                   help="capture whatever the gateway already holds")
    s.set_defaults(fn=cmd_shoot)

    args = p.parse_args(argv)
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
